@startuml
'https://plantuml.com/sequence-diagram

class Item{
String description;
Date time;
boolean complete;
public void setTime(String someTime)
public String getDescription()
public String getTime()
public void setDescription(String descr)
public void setComplete()
public void setIncomplete()
public String getComplete()
}
@enduml